{
 "openapi": "3.0.1",
 "info": {
  "title": "Veteran Service History and Eligibility API",
  "description": "With this API you can\n* Return enrolled benefits for a Veteran.\n* Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by\nthe Affordable Care Act (ACA).  (restricted access).\n* Return disability ratings of a Veteran.\n* Return certain benefit flashes for a Veteran.\n* Return the service history of a Veteran.\n* Confirm an individual's Title 38 Veteran status.\n\nThis information is more detailed than the information returned by the [The Vetera[...]",
  "contact": {
   "name": "VA.gov"
  },
  "version": "2.0.0"
 },
 "servers": [
  {
   "url": "https://sandbox-api.va.gov/services/veteran_verification/{version}",
   "description": "Sandbox",
   "variables": {
    "version": {
     "default": "v2"
    }
   }
  },
  {
   "url": "https://api.va.gov/services/veteran_verification/{version}",
   "description": "Production",
   "variables": {
    "version": {
     "default": "v2"
    }
   }
  }
 ],
 "paths": {
  "/restricted/aca_coverage": {
   "post": {
    "tags": [
     "ACA Coverage"
    ],
    "summary": "Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA). (restricted access).",
    "description": "  This endpoint checks a Veteran's enrollment status for minimum essential\n  coverage (MEC), as defined by the Affordable Care Act (ACA), for a specified\n  date range.\n\n  The response includes a code for Veteran's health benefits status for\n  the request's date range. If the status returned is \"APPLICANT_ENROLLED,\"\n  the response also includes the start and end dates of the coverage. If multiple\n  enrollments are found for the requested date range, multiple start and[...]",
    "operationId": "POST:/restricted/aca_coverage",
    "security": [
     {
      "sandboxOauth2": [
       "aca_coverage_restricted.read"
      ]
     },
     {
      "productionOauth2": [
       "aca_coverage_restricted.read"
      ]
     }
    ]
   }
  },
  "/disability_rating": {
   "get": {
    "tags": [
     "Disability Rating"
    ],
    "summary": "Get information about a Veteran's VA disability ratings. Data returned includes individual and combined ratings, diagnoses, and eligibility dates for compensation for service-connected conditions.",
    "description": "This endpoint provides disability ratings and related decisions and dates for a Veteran, based on the ID in the bearer token.",
    "operationId": "GET:/disability_rating",
    "security": [
     {
      "sandboxOauth2": [
       "disability_rating.read"
      ]
     },
     {
      "productionOauth2": [
       "disability_rating.read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Disability Rating"
    ],
    "summary": "Search for information about a Veteran's VA disability ratings using demographic data. Data returned includes individual and combined ratings, diagnoses, and eligibility dates for compensation for service-connected conditions.",
    "description": "This endpoint provides a Veteran's disability ratings and related decisions and dates.\n\nRequired information:\n* First Name\n* Last Name\n* Date of Birth\n* Street Address\n* City\n* State\n* Country\n* Zipcode\n\nOptional information:\n* Middle Name\n* Gender\n* Mother's Maiden Name\n* Home Phone Number\n* Birth Place City\n* Birth Place State\n* Birth Place Country\n\nTips for finding a match:\n* First and Last Name, Address and DOB are often essential to uniquely identif[...]",
    "operationId": "POST:/disability_rating",
    "security": [
     {
      "sandboxOauth2": [
       "disability_rating.read"
      ]
     },
     {
      "productionOauth2": [
       "disability_rating.read"
      ]
     }
    ]
   }
  },
  "/restricted/disability_rating": {
   "post": {
    "tags": [
     "Disability Rating"
    ],
    "summary": "Search for information about a Veteran's disability rating using Social Security number and demographic data Data returned includes individual and combined ratings, diagnoses, and eligibility dates for compensation for service-connected conditions.(restricted access).",
    "description": "This endpoint provides a Veteran's combined and individual disability ratings and\nrelated decisions and dates. It allows searching for a Veteran using Social Security number and demographic information.\n\nIf using Social Security number, the following information is required:\n* Social Security number\n* First name\n* Last name\n* Birth date\n\nIf using demographic data, the following information is required:\n* First Name\n* Last Name\n* Birth date\n* Street Address\n* Cit[...]",
    "operationId": "POST:/restricted/disability_rating",
    "security": [
     {
      "sandboxOauth2": [
       "disability_rating_restricted.read"
      ]
     },
     {
      "productionOauth2": [
       "disability_rating_restricted.read"
      ]
     }
    ]
   }
  },
  "/summary/disability_rating": {
   "get": {
    "tags": [
     "Disability Rating"
    ],
    "summary": "Get information about a Veteran's VA disability ratings. Data returned includes individual and combined ratings and eligibility dates for compensation for service-connected conditions.",
    "description": "This endpoint provides disability ratings and related decisions and dates for a Veteran, based on the ID in the bearer token.",
    "operationId": "GET:/summary/disability_rating",
    "security": [
     {
      "sandboxOauth2": [
       "disability_rating_summary.read"
      ]
     },
     {
      "productionOauth2": [
       "disability_rating_summary.read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Disability Rating"
    ],
    "summary": "Search for information about a Veteran's VA disability ratings using demographic data. Data returned includes individual and combined ratings and eligibility dates for compensation for service-connected conditions.",
    "description": "This endpoint provides a Veteran's disability ratings and related decisions and dates.\n\nRequired information:\n* First Name\n* Last Name\n* Date of Birth\n* Street Address\n* City\n* State\n* Country\n* Zipcode\n\nOptional information:\n* Middle Name\n* Gender\n* Mother's Maiden Name\n* Home Phone Number\n* Birth Place City\n* Birth Place State\n* Birth Place Country\n\nTips for finding a match:\n* First and Last Name, Address and DOB are often essential to uniquely identif[...]",
    "operationId": "POST:/summary/disability_rating",
    "security": [
     {
      "sandboxOauth2": [
       "disability_rating_summary.read"
      ]
     },
     {
      "productionOauth2": [
       "disability_rating_summary.read"
      ]
     }
    ]
   }
  },
  "/restricted/summary/disability_rating": {
   "post": {
    "tags": [
     "Disability Rating"
    ],
    "summary": "Search for information about a Veteran's VA disability ratings using Social Security number and demographic data. Data returned includes individual and combined ratings and eligibility dates for compensation for service-connected conditions. (restricted access)",
    "description": "This endpoint provides a Veteran's disability ratings and related decisions and dates.   It allows searching for a Veteran using Social   Security number and demographic information.\n\n  If using Social Security number, the following information is required:\n  * Social Security number\n  * First name\n  * Last name\n  * Birth date\n\n  If using demographic data, the following information is required:\n  * First Name\n  * Last Name\n  * Birth date\n  * Street Address\n  * Ci[...]",
    "operationId": "POST:/restricted/summary/disability_rating",
    "security": [
     {
      "sandboxOauth2": [
       "disability_rating_summary_restricted.read"
      ]
     },
     {
      "productionOauth2": [
       "disability_rating_summary_restricted.read"
      ]
     }
    ]
   }
  },
  "/enrolled_benefits": {
   "get": {
    "tags": [
     "Enrolled Benefits"
    ],
    "summary": "Get enrolled benefits information.",
    "description": "This endpoint returns select enrolled benefits for a Veteran.\nIf the Veteran is enrolled, the codes and names for benefits they are\nreceiving will be returned for the following benefit types:\n\n* Compensation (Code C)\n* 306 Pension (Code 306P)\n* Old Law Pension (Code OLP)\n* Improved Pension (Code IP)\n",
    "operationId": "GET:/enrolled_benefits",
    "security": [
     {
      "sandboxOauth2": [
       "enrolled_benefits.read"
      ]
     },
     {
      "productionOauth2": [
       "enrolled_benefits.read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Enrolled Benefits"
    ],
    "summary": "Get enrolled benefits information using demographics to search for the Veteran.",
    "description": "This endpoint returns select enrolled benefits for a Veteran.\nIf the Veteran is enrolled, the codes and names for benefits they are\nreceiving will be returned for the following benefit types:\n\n* Compensation (Code C)\n* 306 Pension (Code 306P)\n* Old Law Pension (Code OLP)\n* Improved Pension (Code IP)\n\nRequired information:\n* First Name\n* Last Name\n* Date of Birth\n* Street Address\n* City\n* State\n* Country\n* Zipcode\n\nOptional information:\n* Middle Name\n* Gen[...]",
    "operationId": "POST:/enrolled_benefits",
    "security": [
     {
      "sandboxOauth2": [
       "enrolled_benefits.read"
      ]
     },
     {
      "productionOauth2": [
       "enrolled_benefits.read"
      ]
     }
    ]
   }
  },
  "/flashes": {
   "get": {
    "tags": [
     "Flashes"
    ],
    "summary": "Retrieve certain benefit flashes associated with a Veteran.",
    "description": "A flash is an attribute on a Veteran's profile that describes special\ncircumstances which can apply to a Veteran. Flashes can aid in\nproperly routing claims or determining eligibility for some VA\nbenefits.\n\nThis endpoint currently shares the following flashes\nif they have been assigned to the Veteran.\n\n* Agent Orange (AO) Exposure Verified\n* Gulf War Veteran PACT Eligibility Verified\n\nIf neither of these flashes exist for the Veteran, then a 200 response\nwith an e[...]",
    "operationId": "GET:/flashes",
    "security": [
     {
      "sandboxOauth2": [
       "flashes.read"
      ]
     },
     {
      "productionOauth2": [
       "flashes.read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Flashes"
    ],
    "summary": "Retrieve certain benefit flashes associated with a Veteran using demographics to search for the Veteran.",
    "description": "A flash is an attribute on a Veteran's profile that describes special\ncircumstances which can apply to a Veteran. Flashes can aid in\nproperly routing claims or determining eligibility for some VA\nbenefits.\n\nThis endpoint currently shares the following flashes\nif they have been assigned to the Veteran.\n\n* Agent Orange (AO) Exposure Verified\n* Gulf War Veteran PACT Eligibility Verified\n\nIf you have a use case for additional flashes, please\ncontact us with the detail[...]",
    "operationId": "POST:/flashes",
    "security": [
     {
      "sandboxOauth2": [
       "flashes.read"
      ]
     },
     {
      "productionOauth2": [
       "flashes.read"
      ]
     }
    ]
   }
  },
  "/service_history": {
   "get": {
    "tags": [
     "Service History"
    ],
    "summary": "Retrieve the service history of a Veteran.",
    "description": "This endpoint provides a Veteran's detailed service history, including all military service episodes with the first and last name of the Veteran, the branch of service, start and end dates, paygrade, discharge status, and separation reason. It also provides start and end dates and locations for each deployment within each episode of service.",
    "operationId": "GET:/service_history",
    "security": [
     {
      "sandboxOauth2": [
       "service_history.read"
      ]
     },
     {
      "productionOauth2": [
       "service_history.read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Service History"
    ],
    "summary": "Retrieve the service history of a Veteran using demographics to search for the Veteran.",
    "description": "This endpoint provides a Veteran's detailed service history including all military\nservice episodes with the first and last name of the Veteran, the branch of service,\nstart and end dates, paygrade, discharge status, and separation reason. It also\nprovides start and end dates and locations for each deployment within each episode\nof service.\n\nRequired information:\n* First Name\n* Last Name\n* Date of Birth\n* Street Address\n* City\n* State\n* Country\n* Zipcode\n\nOpti[...]",
    "operationId": "POST:/service_history",
    "security": [
     {
      "sandboxOauth2": [
       "service_history.read"
      ]
     },
     {
      "productionOauth2": [
       "service_history.read"
      ]
     }
    ]
   }
  },
  "/status": {
   "get": {
    "tags": [
     "Status"
    ],
    "summary": "Confirm whether an individual is a Title 38 Veteran.",
    "description": " Indicates whether an individual is \"Confirmed\" or \"Not Confirmed\" as a\n [Title 38 Veteran](https://www.ecfr.gov/current/title-38) according to VA.\n  ```\"not confirmed\"``` can mean several different things, depending on\n the following not_confirmed_reason values:\n- ```PERSON_NOT_FOUND```: The person was not found in VA source systems\n with the provided information. Including more demographic data\n for a Veteran increases the likelihood of finding their records\n i[...]",
    "operationId": "GET:/status",
    "security": [
     {
      "sandboxOauth2": [
       "veteran_status.read"
      ]
     },
     {
      "productionOauth2": [
       "veteran_status.read"
      ]
     }
    ]
   },
   "post": {
    "tags": [
     "Status"
    ],
    "summary": "Confirm whether an individual is a Title 38 Veteran using demographics",
    "description": "Confirm an individual's Title 38 Veteran status according to VA.\nThis endpoint accepts demographic information for the person to\nbe confirmed and matches it against VA records. If there are\ndifferences between the data entered and the data on file, a\nmatch to a person may not be found. If a successful match is\nidentified, Title 38 Veteran status is checked.\n\n- ```\"confirmed\"``` indicates Title 38 Veteran status.\n- ```\"not confirmed\"``` can mean several different t[...]",
    "operationId": "POST:/status",
    "security": [
     {
      "sandboxOauth2": [
       "veteran_status.read"
      ]
     },
     {
      "productionOauth2": [
       "veteran_status.read"
      ]
     }
    ]
   }
  },
  "/restricted/status": {
   "post": {
    "tags": [
     "Status"
    ],
    "summary": "Confirm whether an individual is a Title 38 veteran using Social Security number and demographics.",
    "description": "Confirm an individual's Title 38 Veteran status according to VA.\nThis endpoint accepts a Social Security number and/or demographic\ninformation for the person to be confirmed and matches it against\nVA records. If there are differences between the data entered and\nthe data on file, a match to a person may not be found. If a\nsuccessful match is identified, Title 38 Veteran status is checked.\n\n- ```\"confirmed\"``` indicates Title 38 Veteran status.\n- ```\"not confirmed\"[...]",
    "operationId": "POST:/restricted/status",
    "security": [
     {
      "sandboxOauth2": [
       "status_restricted.read"
      ]
     },
     {
      "productionOauth2": [
       "status_restricted.read"
      ]
     }
    ]
   }
  }
 },
 "components": {
  "securitySchemes": {
   "productionOauth2": {
    "type": "oauth2",
    "description": "This API uses OAuth 2 with the authorization code grant flow.",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://api.va.gov/oauth2/veteran-verification/system/v1/authorization",
      "tokenUrl": "https://api.va.gov/oauth2/veteran-verification/system/v1/token",
      "scopes": {
       "aca_coverage_restricted.read": "Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).",
       "disability_rating.read": "Retrieve Disability Rating",
       "disability_rating_summary.read": "Retrieve Disability Rating Summary",
       "disability_rating_summary_restricted.read": "For approved federal consumers, view a Veteran's VA disability rating summary using Social Security number and demographic information.",
       "disability_rating_restricted.read": "For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.",
       "enrolled_benefits.read": "Retrieve Veteran Enrolled Benefits",
       "flashes.read": "Retrieve Flashes",
       "service_history.read": "Retrieve Service History",
       "status_restricted.read": "For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.",
       "veteran_status.read": "Retrieve Veteran Status"
      }
     }
    }
   },
   "sandboxOauth2": {
    "type": "oauth2",
    "description": "This API uses OAuth 2 with the authorization code grant flow.",
    "flows": {
     "authorizationCode": {
      "authorizationUrl": "https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/authorization",
      "tokenUrl": "https://sandbox-api.va.gov/oauth2/veteran-verification/system/v1/token",
      "scopes": {
       "aca_coverage_restricted.read": "Return a Veteran's enrollment status in minimum essential coverage (MEC) as defined by the Affordable Care Act (ACA).  (restricted access).",
       "disability_rating.read": "Retrieve Disability Rating",
       "disability_rating_summary.read": "Retrieve Disability Rating Summary",
       "disability_rating_summary_restricted.read": "For approved federal consumers, view a Veteran's VA disability rating summary using Social Security number and demographic information.",
       "disability_rating_restricted.read": "For approved federal consumers, view a Veteran's VA disability ratings and their effective dates using Social Security number and demographic information.",
       "enrolled_benefits.read": "Retrieve Veteran Enrolled Benefits",
       "flashes.read": "Retrieve Flashes",
       "service_history.read": "Retrieve Service History",
       "status_restricted.read": "For approved federal consumers, confirm the Veteran status of an individual using Social Security number and demographic information.",
       "veteran_status.read": "Retrieve Veteran Status"
      }
     }
    }
   }
  }
 }
}